swagger: '2.0'
info:
  title: 自动化运维平台 - 作业平台开放API
  description: 作业平台开放接口文档
  version: 1.0.0
host: '10.88.27.46:4012'
basePath: /openapi
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
  
tags:
  - name: Job
    description: 作业
    
paths:
  /job/run:
    post:
      operationId: run
      summary: 执行指定作业，生成作业执行ID
      description: 执行指定作业，返回对应的作业执行ID（JobExecution）。作业在后台异步执行。|
        作业参数直接在访问参数中指定，作业参数名应避免与系统内置参数重名。
      tags:
        - Job
      parameters:
        - name: job
          in: query
          required: true
          description: 作业名称（全路径）
          type: string
        - name: revision
          in: query
          description: 作业版本号，不指定则默认使用最新版本
          type: string
        - name: async
          in: query
          description: 是否异步执行，不指定则默认为异步执行
          type: boolean
      responses:
        '202':
          description: 请求已接受，返回新建的作业执行ID
          schema:
            type: integer
            format: int64
            description: 新建的作业执行ID
          examples:
            application/json:
              10010010
        '400':
          description: 参数错误
          schema:
            type: string
            description: 错误详细信息
          examples:
            application/json:
              缺少参数'path'
        '404':
          description: 作业不存在
  /job/retrieve:
    get:
      operationId: retrieve
      summary: 查询作业执行状态
      description: 查询作业执行状态
      tags:
        - Job
      parameters:
        - name: id
          in: query
          required: true
          description: 作业执行ID（JobExecution）
          type: integer
          format: int64
      responses:
        '200':
          description: 返回作业执行信息
          schema:
            type: object
            properties:
              executionId:
                type: integer
                format: int64
                description: 作业执行ID
              executionNo:
                type: integer
                description: 作业执行序号，指第几次尝试，目前始终为1
              executionType:
                type: integer
                description: 执行方式（1：手动执行，2：定时执行，3：API调用）
              jobScheduleId:
                type: integer
                format: int64
                description: 对应的定时计划ID（仅当执行方式为“2：定时执行”时有效）
              jobScheduleNo:
                type: integer
                description: 对应的定时计划执行序号（仅当执行方式为“2：定时执行”时有效）
              startTime:
                type: string
                format: date-time
                description: 开始时间
              endTime:
                type: string
                format: date-time
                description: 结束时间
              executedOn:
                type: string
                format: date-time
                description: 请求执行时间
              executedBy:
                type: string
                description: 请求执行人
              status:
                type: integer
                description: 当前状态（0：未开始，1：运行中，2：成功，3：失败）
              steps:
                type: array
                description: 执行步骤明细
                items:
                  type: object
                  properties:
                    stepExecutionId:
                      type: integer
                      format: int64
                      description: 步骤执行ID
                    sortNo:
                      type: integer
                      description: 步骤序号
                    startTime:
                      type: string
                      format: date-time
                      description: 开始时间
                    endTime:
                      type: string
                      format: date-time
                      description: 结束时间
                    status:
                      type: integer
                      description: 当前状态（0：未开始，1：运行中，2：成功，3：失败）
                    uows:
                      type: array
                      description: 执行单元
                      items:
                        type: object
                        properties:
                          id:
                            type: integer
                            format: int64
                            description: UOW ID
                          agent:
                            type: object
                            description: 作业代理
                            properties:
                              id:
                                type: integer
                                format: int64
                                description: 作业代理ID
                              name:
                                type: string
                                description: 作业代理名称
                              zoneId:
                                type: string
                                description: 可用区ID
                              serverId:
                                type: string
                                description: 工作节点主机ID
                              status:
                                type: integer
                                description: 作业代理状态（1：可用，2：不可用）
                          command:
                            type: string
                            description: 执行命令
                          console:
                            type: string
                            description: 工作节点控制台输出
                          exitCode:
                            type: integer
                            description: 命令返回码
                          errorMessage:
                            type: string
                            description: 异常出错信息
                          startTime:
                            type: string
                            format: date-time
                            description: 开始时间
                          endTime:
                            type: string
                            format: date-time
                            description: 结束时间
                          status:
                            type: integer
                            description: 当前状态（0：未开始，1：运行中，2：成功，3：失败）
                          targets:
                            type: array
                            items:
                              type: object
                              properties:
                                targetResourceId:
                                  type: string
                                  description: 目标资源ID
                                startTime:
                                  type: string
                                  format: date-time
                                  description: 开始时间
                                endTime:
                                  type: string
                                  format: date-time
                                  description: 结束时间
                                console:
                                  type: string
                                  description: 目标控制台输出
                                status:
                                  type: integer
                                  description: 当前状态（0：未开始，1：运行中，2：成功，3：失败）
          examples:
            application/json:
              - executionId: 142
                executionNo: 1
                executionType: 3
                jobScheduleId: null
                jobScheduleNo: null
                startTime: '2018-04-25 06:32:10'
                endTime: '2018-04-25 06:32:11'
                executedOn: '2018-04-25 06:32:10'
                executedBy: 'DM'
                status: 2
                steps:
                  - stepExecutionId: 138
                    sortNo: 1
                    startTime: '2018-04-25 06:32:10'
                    endTime: '2018-04-25 06:32:11'
                    status: 2
                    uows:
                      - id: 762
                        agent:
                          id: 1
                          name: 'JPAgent1'
                          zoneId: '10906161429191065756'
                          serverId: '10906161429191066136'
                          status: 1
                        command: 'echo Hello Allan'
                        console:
                        exitCode:
                        errorMessage:
                        startTime: '2018-04-25 06:32:10'
                        endTime: '2018-04-25 06:32:11'
                        status: 2
                        targets:
                          - targetResourceId: '10906161429191065756'
                            startTime: '2018-04-25 06:32:10'
                            endTime: '2018-04-25 06:32:11'
                            console: '>ssh 10.88.27.46 \"bash -s\" < /service/jp/agent/uow762.script\nHello Allan\n'
                            status: 2
                    
                    
            
